--    uniCenta oPOS - Touch Friendly Point Of Sale
--    Copyright (c) 2009-2014 uniCenta
--    http://sourceforge.net/projects/unicentaopos
--
--    This file is part of uniCenta oPOS.
--
--    uniCenta oPOS is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    uniCenta oPOS is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

-- Database create script for MySQL
-- Copyright (c) 2009-2014 uniCenta

ALTER TABLE PEOPLE DROP CONSTRAINT PEOPLE_FK_1;
ALTER TABLE ATTRIBUTEINSTANCE DROP CONSTRAINT ATTINST_SET;
ALTER TABLE ATTRIBUTEINSTANCE DROP CONSTRAINT ATTINST_ATT;
ALTER TABLE ATTRIBUTESETINSTANCE DROP CONSTRAINT ATTSETINST_SET;
ALTER TABLE ATTRIBUTEUSE DROP CONSTRAINT ATTUSE_SET;
ALTER TABLE ATTRIBUTEUSE DROP CONSTRAINT ATTUSE_ATT;
ALTER TABLE ATTRIBUTEVALUE DROP CONSTRAINT ATTVAL_ATT;
ALTER TABLE CATEGORIES DROP CONSTRAINT CATEGORIES_FK_1;
ALTER TABLE CUSTOMERS DROP CONSTRAINT CUSTOMERS_TAXCAT;
ALTER TABLE LEAVES DROP CONSTRAINT lEAVES_PPLID;
ALTER TABLE PAYMENTS DROP CONSTRAINT PAYMENTS_FK_RECEIPT;
ALTER TABLE PLACES DROP CONSTRAINT PLACES_FK_1;
ALTER TABLE PRODUCTS DROP CONSTRAINT PRODUCTS_ATTRSET_FK;
ALTER TABLE PRODUCTS DROP CONSTRAINT PRODUCTS_TAXCAT_FK;
ALTER TABLE PRODUCTS DROP CONSTRAINT PRODUCTS_FK_1;
ALTER TABLE PRODUCTS_CAT DROP CONSTRAINT PRODUCTS_CAT_FK_1;
ALTER TABLE PRODUCTS_COM DROP CONSTRAINT PRODUCTS_COM_FK_1;
ALTER TABLE PRODUCTS_COM DROP CONSTRAINT PRODUCTS_COM_FK_2;
ALTER TABLE RECEIPTS DROP CONSTRAINT RECEIPTS_FK_MONEY;
ALTER TABLE RESERVATION_CUSTOMERS DROP CONSTRAINT RES_CUST_FK_1;
ALTER TABLE RESERVATION_CUSTOMERS DROP CONSTRAINT RES_CUST_FK_2;
ALTER TABLE SHIFT_BREAKS DROP CONSTRAINT SHIFT_BREAKS_BREAKID;
ALTER TABLE SHIFT_BREAKS DROP CONSTRAINT SHIFT_BREAKS_SHIFTID;
ALTER TABLE STOCKCURRENT DROP CONSTRAINT STOCKCURRENT_ATTSETINST;
ALTER TABLE STOCKCURRENT DROP CONSTRAINT STOCKCURRENT_FK_1;
ALTER TABLE STOCKCURRENT DROP CONSTRAINT STOCKCURRENT_FK_2;
ALTER TABLE STOCKDIARY DROP CONSTRAINT STOCKDIARY_ATTSETINST;
ALTER TABLE STOCKDIARY DROP CONSTRAINT STOCKDIARY_FK_1;
ALTER TABLE STOCKDIARY DROP CONSTRAINT STOCKDIARY_FK_2;
ALTER TABLE STOCKLEVEL DROP CONSTRAINT STOCKLEVEL_PRODUCT;
ALTER TABLE STOCKLEVEL DROP CONSTRAINT STOCKLEVEL_LOCATION;
ALTER TABLE TAXES DROP CONSTRAINT TAXES_CAT_FK;
ALTER TABLE TAXES DROP CONSTRAINT TAXES_CUSTCAT_FK;
ALTER TABLE TAXES DROP CONSTRAINT TAXES_TAXES_FK;
ALTER TABLE TAXLINES DROP CONSTRAINT TAXLINES_TAX;
ALTER TABLE TAXLINES DROP CONSTRAINT TAXLINES_RECEIPT;
ALTER TABLE TICKETLINES DROP CONSTRAINT TICKETLINES_ATTSETINST;
ALTER TABLE TICKETLINES DROP CONSTRAINT TICKETLINES_FK_TICKET;
ALTER TABLE TICKETLINES DROP CONSTRAINT TICKETLINES_FK_2;
ALTER TABLE TICKETLINES DROP CONSTRAINT TICKETLINES_FK_3;
ALTER TABLE TICKETS DROP CONSTRAINT TICKETS_CUSTOMERS_FK;
ALTER TABLE TICKETS DROP CONSTRAINT TICKETS_FK_2;
ALTER TABLE TICKETS DROP CONSTRAINT TICKETS_FK_ID;

-- DROP DEFAULT DATA
DELETE FROM ROLES;
DELETE FROM PEOPLE;
DELETE FROM RESOURCES;
DELETE FROM CATEGORIES;
DELETE FROM TAXCATEGORIES;
DELETE FROM TAXES;
DELETE FROM LOCATIONS;
DELETE FROM FLOORS;
DELETE FROM PLACES;
DELETE FROM SHIFTS;
DELETE FROM BREAKS;
DELETE FROM SHIFT_BREAKS;